### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by ViralBShah**
I am setting up juliaimages.org to point to this website.

### CODE REVIEW

**Comment by timholy** [comment]
I don't know anything about this stuff, but I trust you do, so merging. Thanks!

**Comment by ViralBShah** [comment]
If you can make me owner of the org temporarily, I can complete the rest of the setup for you.

**Comment by ViralBShah** [comment]
I would need the owner role to be set for me here:
https://github.com/orgs/JuliaImages/people

**Comment by timholy** [comment]
Done

**Pull request merged**
