### PR TITLE
Create imagetransformations.md

### PR DESCRIPTION
**Pull request by JeffFessler**
Seems to be no docs for ImageTransformations yet so this is a starting point.

### CODE REVIEW

**Comment by johnnychen94** [comment]
Thanks!

LGTM, and don't forget to register the new md file in `make.jl`
```diff
--- a/docs/make.jl
+++ b/docs/make.jl
@@ -18,6 +18,7 @@ makedocs(modules  = [Images, ImageCore, Colors, ColorTypes, FixedPointNumbers, I
                          "imagemetadata.md",
                          "imagesegmentation.md",
                          "imagefeatures.md",
+                         "imagetransformations.md",
                          "troubleshooting.md",
                      ],
                      "Demos" => Any[
```

**Comment by JeffFessler** [comment]
Ok, done in PR #55

**Comment by JeffFessler** [comment]
Oops, I see now that I could have done that to the same branch. 
Let me know if you need me to merge them...  I'm still new to this...

**Comment by johnnychen94** [comment]
yes, you can keep pushing new commits to the PR branch, and the PR status gets updated automatically until it's merged. 😄

**Comment by JeffFessler** [comment]
Thanks for the tips.  I made all these changes in the browser!  :)

**Pull request merged**
