### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Hey Pietro, Looking good and thanks for contributing! Let me know when you done

**Comment by pitmonticone** [comment]
Hi @ashwani-rathee, I've just finished. 

Let me know if you believe it could be helpful if I join this GitHub organisation as a member. I'll certainly review the docs of all JuliaImages packages as soon as I find the time.

Hope it helps.

**Comment by ashwani-rathee** [comment]
Thanks for the help! It would be great to see you contribute more before any of us would be confident enough for that decision. And current PR does help 😄

**Review by ashwanirathee — APPROVED** [review]
Looks good

**Comment by pitmonticone** [comment]
Did the same for a few other packages with the little time available at the moment.

**Pull request merged**
