### PR TITLE
Add missing fields for scikit-image+Numpy in api_comparision.md

### PR DESCRIPTION
**Pull request by mgautam98**
Hey

I have added some of the missing fields for scikit-image in api_comparision.md

Histogram matching - http://scikit-image.org/docs/dev/api/skimage.transform.html#match-histograms
Entropy - http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#entropy
Min/max/mean - http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#minimum
                           http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#maximum
                           http://scikit-image.org/docs/dev/api/skimage.filters.rank.html#mean

### CODE REVIEW

**Comment by mgautam98** [comment]
@timholy @zygmuntszpak

**Comment by johnnychen94** [comment]
Hi, Gautam
Thanks for your contribution!
The update to `api_comparison` is great, can you delete the demo part of this PR so that I can merge this.

**Comment by mgautam98** [comment]
I have deleted the fork so I can not make any changes to it. You can close this PR.

**Comment by johnnychen94** [comment]
Alright, I was thinking you to make it a PR. I'll do it later.

**Pull request closed without merging**
