### PR TITLE
replace travis with github action

### PR DESCRIPTION
**Pull request by johnnychen94**
Before we figure out what happens to #98, another option is to deploy the docs using Github Action

### CODE REVIEW

**Comment by johnnychen94** [comment]
Hmmm, seems that julia 1.0 on github action is also affected 😕

**Comment by timholy** [comment]
Likely also noted in https://travis-ci.org/JuliaImages/Images.jl/jobs/624338186?utm_medium=notification&utm_source=github_status

**Comment by timholy** [comment]
This is not a JuliaImages problem, it's a Julia problem. I've been able to replicate this locally with julia-1.0.5 (but not julia-1.0.0), and am running a `git bisect` now.

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/issues/34121. Probably a WIP.

**Pull request closed without merging**
