### PR TITLE
sujoy edge demo

### PR DESCRIPTION
**Pull request by amarbit**
Hi 
please accept the demo. I locally build the demo and checked and it was working.

### CODE REVIEW

**Comment by johnnychen94** [comment]
Thanks for doing this.

It's a bit tricky that the default branch in this repo is `source` instead of `master`. `master` is the branch to hold all automatically generated things.

This is to say. The new demo should be added in `source` branch and the PR should be opened from your `source` branch to this repo's `source` branch. (Currently it is `master` -> `source`)

**Comment by amarbit** [comment]
Hi
I am trying to push a demo card example created,but push showing access
error. Could you suggest the steps to commit the demo code.

Regards
Amar kumar

**Comment by johnnychen94** [comment]
If you're not familar with git, the best strategy is to keep a copy of your new demo file, and then do it again.

1. clone this repo: `git clone git@github.com:JuliaImages/juliaimages.github.io.git`
2. enter the folder: `cd juliaimages.github.io`
3. [important] checkout to `source` branch (not `master` branch)
4. add your demos, and use `git add` to stage the files and then `git commit` to create a new commit
5. push to your upstream fork with `git push` and then create a new PR for it.

I think that's all of it.

**Comment by johnnychen94** [comment]
close this in favor of #158

**Pull request closed without merging**
